version: "3"

services:
  postgres:
    container_name: compose_postgres
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${DB_NAME:-composedb}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
    volumes:
      - ${POSTGRES_DATA_PATH:-./data/postgres}:/var/lib/postgresql/data
  
  redis:
    container_name: compose_redis
    image: redis:alpine
    volumes:
      - ${REDIS_DATA_PATH:-./data/redis}:/data

  compose:
    container_name: compose
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG:-TRUE}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI:-postgres://postgres:postgres@postgres:5432/composedb}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL:-redis://redis:6379}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND:-redis}
    depends_on: 
      - postgres
      - redis
